import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {Sidebar} from "../components/Sidebar";

const Home: NextPage = () => {
  return (
    <div>

      <Head>
        <title>Solo Message</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>


          <Sidebar/>


      </main>

    </div>
  )
}

export default Home
