import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {Sidebar} from "../components/Sidebar";

const Home: NextPage = () => {
  return (
    <div>

      <Head>
        <title>Solo Message</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
                integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
                crossOrigin="anonymous"/>
      </Head>

      <main>


          <Sidebar/>


      </main>

    </div>
  )
}

export default Home
